version: 0.2

#
# AWS CodeBuild spec, to build locally on your desktop use one of these -
#  codebuild_build.sh -c -b ./buildspec-webserver.yml  -i public.ecr.aws/k8x9x6i3/evolphin-pico/aws-codebuild-env:1.0  -a ../out/
#  codebuild_build.sh -c -p $AWS_DEFAULT_PROFILE  -b ./buildspec-webserver.yml  -i public.ecr.aws/k8x9x6i3/evolphin-pico/aws-codebuild-env:1.0  -a ../out/ -e /tmp/code.env
env:
  variables:
    CI: "true"
phases:
  install:
    on-failure: ABORT
    commands:
      - npm install --no-optional
  build:
    on-failure: ABORT
    commands:
      - echo Cypress run started
      # Script below will return [daisy, dev, beta, prod, unknown] based on branch name [Development/Daisy, Deployment/Dev, Deployment/Staging, Deployment/Prod, *any thing else*]
      - git branch --show-current
      #run cypress in desired environment that is connected to cypress cloud
      - "cypress run --e2e --config baseUrl=https://app.dev.crop.photo --record --key 60804ff0-c839-446b-93bc-a8af516e5c89"
    reports:
      junit-web-server-reports:
        files:
          - "**/TEST-*.xml"
        base-directory: "cypress/reports/test-results"
        file-format: JUNITXML
        discard-paths: no
    finally:
      - rm -rf /root/.npm
